app = "app-enollgay"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  DATABASE_URL = "sqlite:///./app.db"
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
